version: '3'

services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.test
        ports: 
            - "4001:3000"
        volumes:
            - /opt/app/node_modules